version: '2'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    image: vashi9/nod-mongo
    ports:
      - '5005:3000'
    link:
      - mongo
    /*deploy:
      mode: replicated
      replicas: 3 /*

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '5006:27017'
    deploy:
      mode: replicated
      replicas: 3   
      
