version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '5005:5005'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '5006:27017'
© 2019 GitHub, Inc.
